name: CI

# Trigger workflow on push and pull requests.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies with a clean slate
        run: npm ci
      - name: Run tests
        run: npm run test
